modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ConcreteConversion/master/update.json"
displayURL="${mod_homepage}"
logoFile="logo.png"
logoBlur=false
authors="${mod_author}"
description="${mod_desc}"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[modproperties.${mod_id}]
    configuredBackground="minecraft:textures/block/blue_concrete.png"
