modLoader="javafml"
loaderVersion="[32,)"
logoFile="ConcreteConversionLogo.png"
[[mods]]
	modId="concreteconversion"
	version="1.16.1-4.1.1.0"
	displayName="Concrete Conversion"
	updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ModUpdateFiles/master/ConcreteConversion.json"
	issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/concrete-conversion/issues"
	displayURL="https://minecraft.curseforge.com/projects/concrete-conversion"
	authors="mrp_v2, coolsim"
	description='''Adds a new, easy way to convert concrete powder into concrete.'''
[[dependencies.concreteconversion]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.concreteconversion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
