modLoader="javafml"
loaderVersion="[28,)"
logoFile="ConcreteConversionLogo.png"
[[mods]]
	modId="concreteconversion"
	version="${version}"
	displayName="Concrete Conversion"
	updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ModUpdateFiles/master/ConcreteConversion.json"
	issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/concrete-conversion/issues"
	displayURL="https://minecraft.curseforge.com/projects/concrete-conversion"
	credits="Thanks to coolsim for help with porting to 1.14"
	authors="mrp_v2, coolsim"
	description='''Adds a new, easy way to convert concrete powder into concrete.'''
[[dependencies.concreteconversion]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.concreteconversion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
